# Generated by Django 4.0.5 on 2022-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsoCpu',
            fields=[
                ('pid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridad', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uso_cpu',
            },
        ),
        migrations.CreateModel(
            name='UsoMemoria',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.PositiveIntegerField(blank=True, null=True)),
                ('prioridad', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uso_memoria',
            },
        ),
    ]
